import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { GRADES, STRUGGLE_CATEGORIES } from '@/types';
import { Sparkles, Printer, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

export function SupportPlanTab() {
  const [gradeLevel, setGradeLevel] = useState('');
  const [specialConsiderations, setSpecialConsiderations] = useState<string[]>([]);
  const [selectedStruggles, setSelectedStruggles] = useState<string[]>([]);
  
  // Student Portrait
  const [primaryConcern, setPrimaryConcern] = useState('');
  const [strengths, setStrengths] = useState('');
  const [additionalContext, setAdditionalContext] = useState('');
  const [stressors, setStressors] = useState('');
  const [strategiesThatWorked, setStrategiesThatWorked] = useState('');
  const [whatHasntWorked, setWhatHasntWorked] = useState('');
  
  // Generated plan
  const [generatedPlan, setGeneratedPlan] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);

  const specialConsiderationOptions = [
    { id: 'ell', label: 'ELL', description: 'English Language Learner' },
    { id: 'fi', label: 'French Immersion', description: 'Student is in FI program' },
    { id: 'iep', label: 'IEP', description: 'Individual Education Plan' },
  ];

  const toggleSpecialConsideration = (id: string) => {
    setSpecialConsiderations(prev => 
      prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]
    );
  };

  const toggleStruggle = (struggle: string) => {
    setSelectedStruggles(prev =>
      prev.includes(struggle) ? prev.filter(s => s !== struggle) : [...prev, struggle]
    );
  };

  const handleGenerate = async () => {
    if (!gradeLevel || selectedStruggles.length === 0) {
      toast.error('Please select grade level and at least one struggle area');
      return;
    }

    setIsGenerating(true);
    
    // Simulate API call - replace with actual Firebase Cloud Function call
    try {
      // This would call your Firebase Cloud Function
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      setGeneratedPlan(`
# Support Plan for Grade ${gradeLevel} Student

## Profile Summary
- Grade: ${gradeLevel}
- Special Considerations: ${specialConsiderations.join(', ') || 'None specified'}
- Primary Concern: ${primaryConcern || 'Not specified'}

## Identified Struggle Areas
${selectedStruggles.map(s => `- ${s}`).join('\n')}

## Strengths & Assets
${strengths || 'To be documented'}

## Recommended Strategies

### Classroom Accommodations
1. Provide visual supports and graphic organizers
2. Break tasks into smaller, manageable chunks
3. Allow for movement breaks
4. Use preferential seating near instruction

### Intervention Approaches
1. Small group instruction targeting specific skills
2. One-on-one conferencing for feedback
3. Peer tutoring opportunities
4. Technology-assisted learning tools

### Communication Plan
- Regular home-school communication log
- Weekly progress updates
- Parent conference scheduled for [date]

## Monitoring & Review
- Review date: [4 weeks from start]
- Success indicators to track
- Data collection methods

---
*Generated by AI Support Plan Generator*
      `);
      
      toast.success('Support plan generated!');
    } catch (error) {
      toast.error('Failed to generate plan. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="outline" size="sm">
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        <h1 className="text-2xl font-bold">Support Plan</h1>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Student Support Plan Generator</CardTitle>
          <p className="text-sm text-muted-foreground">
            Grades 1-5 • Academics & Learning Skills (Ontario)
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Student Profile */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="space-y-4">
              <h3 className="font-semibold">Student Profile</h3>
              <div className="space-y-2">
                <Label>Grade Level</Label>
                <Select value={gradeLevel} onValueChange={setGradeLevel}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select Grade..." />
                  </SelectTrigger>
                  <SelectContent>
                    {GRADES.filter(g => ['1', '2', '3', '4', '5'].includes(g)).map(g => (
                      <SelectItem key={g} value={g}>Grade {g}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
            
            <div className="space-y-4">
              <h3 className="font-semibold">Special Considerations</h3>
              <div className="space-y-2">
                {specialConsiderationOptions.map(option => (
                  <div key={option.id} className="flex items-start space-x-2">
                    <Checkbox
                      id={option.id}
                      checked={specialConsiderations.includes(option.id)}
                      onCheckedChange={() => toggleSpecialConsideration(option.id)}
                    />
                    <div className="grid gap-1 leading-none">
                      <Label htmlFor={option.id} className="font-medium">{option.label}</Label>
                      <p className="text-xs text-muted-foreground">{option.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Observed Struggles */}
          <div className="space-y-4">
            <h3 className="font-semibold">Observed Struggles</h3>
            <p className="text-sm text-muted-foreground">Click chips to select. Choose only what matters.</p>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-4">
              {/* Learning Skills */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Learning Skills & Work Habits</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.learningSkills.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>

              {/* Literacy: Reading */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Literacy: Reading</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.literacyReading.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>

              {/* Literacy: Writing */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Literacy: Writing</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.literacyWriting.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>

              {/* Literacy: Oral Communication */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Literacy: Oral Communication</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.literacyOral.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>

              {/* Numeracy */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Numeracy (Math)</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.numeracy.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>

              {/* French Immersion */}
              <div className="space-y-2">
                <h4 className="text-sm font-medium">French Immersion (Language)</h4>
                <div className="flex flex-wrap gap-2">
                  {STRUGGLE_CATEGORIES.frenchImmersion.map(struggle => (
                    <Button
                      key={struggle}
                      variant={selectedStruggles.includes(struggle) ? "default" : "outline"}
                      size="sm"
                      onClick={() => toggleStruggle(struggle)}
                    >
                      {struggle}
                    </Button>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Student Portrait */}
          <div className="space-y-4">
            <h3 className="font-semibold">Student Portrait (Context & Assets)</h3>
            <p className="text-sm text-muted-foreground">This is the part that makes the plan "real."</p>
            
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Primary Concern / Summary of Need</Label>
                <Textarea
                  placeholder="e.g., strong oral communicator but refuses to write..."
                  value={primaryConcern}
                  onChange={(e) => setPrimaryConcern(e.target.value)}
                  rows={3}
                />
              </div>
              
              <div className="space-y-2">
                <Label>Strengths, Interests & Hopes</Label>
                <Textarea
                  placeholder="e.g., loves Minecraft, artistic, kind to peers..."
                  value={strengths}
                  onChange={(e) => setStrengths(e.target.value)}
                  rows={3}
                />
              </div>
              
              <div className="space-y-2">
                <Label>Additional Context (optional & confidential)</Label>
                <Textarea
                  placeholder="e.g., recent family change, medical factors..."
                  value={additionalContext}
                  onChange={(e) => setAdditionalContext(e.target.value)}
                  rows={3}
                />
              </div>
              
              <div className="space-y-2">
                <Label>Stressors & What Helps De-escalate</Label>
                <Textarea
                  placeholder="e.g., transitions, loud noise; breaks help..."
                  value={stressors}
                  onChange={(e) => setStressors(e.target.value)}
                  rows={3}
                />
              </div>
              
              <div className="space-y-2">
                <Label>Strategies That Have Worked (even briefly)</Label>
                <Textarea
                  placeholder="e.g., visual timers, choice boards..."
                  value={strategiesThatWorked}
                  onChange={(e) => setStrategiesThatWorked(e.target.value)}
                  rows={3}
                />
              </div>
              
              <div className="space-y-2">
                <Label>What Hasn't Worked / Still Puzzling</Label>
                <Textarea
                  placeholder="e.g., public praise shuts them down..."
                  value={whatHasntWorked}
                  onChange={(e) => setWhatHasntWorked(e.target.value)}
                  rows={3}
                />
              </div>
            </div>
          </div>

          {/* Generate Button */}
          <div className="flex gap-4">
            <Button onClick={handleGenerate} disabled={isGenerating} className="flex-1">
              <Sparkles className="h-4 w-4 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate Support Plan'}
            </Button>
            <Button variant="outline" onClick={handlePrint}>
              <Printer className="h-4 w-4 mr-2" />
              Print / Save as PDF
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Tip: use Print → Save as PDF.
          </p>
        </CardContent>
      </Card>

      {/* Generated Plan */}
      <Card>
        <CardHeader>
          <CardTitle>Generated Support Plan</CardTitle>
          <p className="text-sm text-muted-foreground">
            You can edit the text below before printing.
          </p>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label>Plan text (editable)</Label>
              <Textarea
                value={generatedPlan}
                onChange={(e) => setGeneratedPlan(e.target.value)}
                rows={20}
                placeholder="Your generated plan will appear here..."
                className="font-mono text-sm"
              />
            </div>
            <div className="space-y-2">
              <Label>Preview</Label>
              <div className="border rounded-lg p-4 min-h-[400px] bg-muted/50 overflow-auto">
                {generatedPlan ? (
                  <div className="prose prose-sm max-w-none whitespace-pre-wrap">
                    {generatedPlan}
                  </div>
                ) : (
                  <p className="text-muted-foreground text-center py-8">
                    Your generated plan will appear here...
                  </p>
                )}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
